// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain


Texture2D<float> Input;

// Create a RenderTexture with enableRandomWrite flag and set it
RWTexture2D<float4> Result;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // convert a single-channel float texture to a grayscale float
    float p = Input[id.xy];
    Result[id.xy] = float4(p, p, p, 1);
}
