// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

Texture2D<float3> Input;

// Create a RenderTexture with enableRandomWrite flag and set it
RWTexture2D<float4> Result;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // add alpha to 3-channel float data
    float3 p = Input[id.xy];
    Result[id.xy] = float4(p.x, p.y, p.z, 1);
}
